### ISSUE TITLE
Is version 0.35.0 is still safe now?

### ISSUE THREAD

**Issue by quangpc-zz** [lsapan/pgoapi-swift#57]
As the information on this link:
https://www.reddit.com/r/pokemongodev/comments/54j1y8/0350_is_now_dead_upgrade_to_continue/
I notice that:
"minimum_client_version": "0.39.0"
so user need upgrade app the latest version to continue playing.
I afraid we can be banned by using api now. Do u have any idea? Thanks!

**Comment by PokemonGoSucks** [comment]
It's no longer safe and this api should not be used. There are a few real clients that are still up and running in 0.35 because the app was never closed, but that's just a handful of people. I was trying to manually deobfuscate some of the functions in the lib.so, so we'll see if the reverse engineering gets anywhere. Basically looking for anything that could produce the 32 bit seed.

Looks like we'll need to do dynamic deobfuscating/realtime, so this goes beyond my abilities. Hopefully the #re team can figure this out.
