### ISSUE TITLE
InvalidProtocolBuffer("Invalid Tag: after tag 60")

### ISSUE THREAD

**Issue by lucamegh** [lsapan/pgoapi-swift#7]
`fatal error: 'try!' expression unexpectedly raised an error: ProtocolBuffers.ProtocolBuffersError.InvalidProtocolBuffer("Invalid Tag: after tag 60"): file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.8/src/swift/stdlib/public/core/ErrorType.swift, line 54`

New error when getting map objects. That does not happen always. Guess it happens only when a pokémon is found?

**Comment by lsapan** [comment]
Are you using the latest version of the `protos` directory? I updated it yesterday, just want to make sure that's the copy you're using. The other thing to consider is it's possible the server is returning an error (just because they're overloaded). If that's the case, we'll just need to `try` instead of `try!`

**Comment by lucamegh** [comment]
Yes, I'm using the latest version. Yes I've changed it and it worked. Just didn't know if something I was allowed to do. Thanks

**Comment by lucamegh** [comment]
Also @lsapan, I'd like to donate you money in return for further help with your API. I hope it is ok with you! If so, tell me where I can contact you privately. I'd appreciate it

**Comment by lsapan** [comment]
My apologies I never got back to you. I'm glad that fixed it. I can't accept your money, but I'm sure myself or the community would be happy to help you.
